export const GAME_ASSET_MANIFEST = [
	{ alias: "skyDay", src: "/assets/scene/skyes/sky_day.png" },
	{ alias: "skyEvening", src: "/assets/scene/skyes/sky_evening.png" },
	{ alias: "skyNight", src: "/assets/scene/skyes/sky_night.png" },
	{ alias: "darkSpaceSky", src: "/assets/scene/skyes/dark_space_skyes.webp" },
	{ alias: "starsSvg", src: "/assets/scene/star/stars.svg" },
	{
		alias: "cloudsStripDay",
		src: "/assets/scene/clouds/clouds_strip_day.svg",
	},
	{
		alias: "cloudsStripEvening",
		src: "/assets/scene/clouds/clouds_strip_evening.svg",
	},
	{
		alias: "cloudsStripNight",
		src: "/assets/scene/clouds/clouds_strip_night.svg",
	},
	{ alias: "basicMapDay", src: "/assets/backgrounds/basic_map_day.png" },
	{
		alias: "basicMapEvening",
		src: "/assets/backgrounds/basic_map_evening.png",
	},
	{ alias: "basicMapNight", src: "/assets/backgrounds/basic_map_night.png" },
	{ alias: "starsOverlay", src: "/assets/scene/star/stars_overlay.webp" },
	{ alias: "sun", src: "/assets/scene/moon_sun/sun.png" },
	{ alias: "moon", src: "/assets/scene/moon_sun/moon.png" },
	{ alias: "back", src: "/assets/scene/back/back.png" },
	{ alias: "middle", src: "/assets/scene/middle/middle.png" },
	{ alias: "front", src: "/assets/scene/front/front.png" },
	{ alias: "back1", src: "/assets/scene/back/back_1.svg" },
	{ alias: "back2", src: "/assets/scene/back/back_2.svg" },
	{ alias: "back3", src: "/assets/scene/back/back_3.svg" },
	{ alias: "back4", src: "/assets/scene/back/back_4.svg" },
	{ alias: "back5", src: "/assets/scene/back/back_5.svg" },
	{ alias: "back6", src: "/assets/scene/back/back_6.svg" },
	{ alias: "middle1", src: "/assets/scene/middle/middle_1.svg" },
	{ alias: "middle2", src: "/assets/scene/middle/middle_2.svg" },
	{ alias: "middle3", src: "/assets/scene/middle/middle_3.svg" },
	{ alias: "middle4", src: "/assets/scene/middle/middle_4.svg" },
	{ alias: "middle5", src: "/assets/scene/middle/middle_5.svg" },
	{ alias: "middle6", src: "/assets/scene/middle/middle_6.svg" },
	{ alias: "middleDog", src: "/assets/scene/middle/middle_dog.svg" },
	{ alias: "middleGirls", src: "/assets/scene/middle/middle_girls.svg" },
	{ alias: "middleSnake", src: "/assets/scene/middle/middle_snake.svg" },
	{
		alias: "middleAngryPlayers",
		src: "/assets/scene/middle/middle_angry_players.svg",
	},
	{ alias: "front1", src: "/assets/scene/front/front_1.svg" },
	{ alias: "front2", src: "/assets/scene/front/front_2.svg" },
	{ alias: "front3", src: "/assets/scene/front/front_3.svg" },
	{ alias: "front4", src: "/assets/scene/front/front_4.svg" },
	{ alias: "front5", src: "/assets/scene/front/front_5.svg" },
	{ alias: "front6", src: "/assets/scene/front/front_6.svg" },
	{ alias: "frontHole", src: "/assets/scene/front/front_hole_1.svg" },
	{ alias: "frontBush1", src: "/assets/scene/front/front_bush_1.svg" },
	{ alias: "frontBush2", src: "/assets/scene/front/front_bush_2.svg" },
	{ alias: "frontBush3", src: "/assets/scene/front/front_bush_3.svg" },
	{ alias: "frontBush4", src: "/assets/scene/front/front_bush_3.svg" },
	{ alias: "waterTrap1", src: "/assets/scene/traps/water_trap_1.svg" },
	{ alias: "waterTrap2", src: "/assets/scene/traps/water_trap_2.svg" },
	{ alias: "waterTrap3", src: "/assets/scene/traps/water_trap_3.svg" },
	{ alias: "waterTrap4", src: "/assets/scene/traps/water_trap_4.svg" },
	{ alias: "water_trap_1", src: "/assets/scene/traps/water_trap_1.svg" },
	{ alias: "water_trap_2", src: "/assets/scene/traps/water_trap_2.svg" },
	{ alias: "water_trap_3", src: "/assets/scene/traps/water_trap_3.svg" },
	{ alias: "water_trap_4", src: "/assets/scene/traps/water_trap_4.svg" },
	{ alias: "sand_trap_1", src: "/assets/scene/traps/sand_trap_1.svg" },
	{ alias: "sand_trap_2", src: "/assets/scene/traps/sand_trap_2.svg" },
	{ alias: "water1", src: "/assets/scene/traps/water_trap_1.svg" },
	{ alias: "water2", src: "/assets/scene/traps/water_trap_2.svg" },
	{ alias: "water3", src: "/assets/scene/traps/water_trap_3.svg" },
	{ alias: "water4", src: "/assets/scene/traps/water_trap_4.svg" },
	{ alias: "water5", src: "/assets/scene/traps/water_trap_2.svg" },
	{ alias: "sand1", src: "/assets/scene/traps/sand_trap_1.svg" },
	{ alias: "sand2", src: "/assets/scene/traps/sand_trap_2.svg" },
	{ alias: "sandTrap1", src: "/assets/scene/traps/sand_trap_1.svg" },
	{ alias: "sandTrap2", src: "/assets/scene/traps/sand_trap_2.svg" },
	{ alias: "midBush1", src: "/assets/scene/middle/mid_bush_1.png" },
	{ alias: "midBush2", src: "/assets/scene/middle/mid_bush_2.png" },
	{ alias: "midBush3", src: "/assets/scene/middle/mid_bush_3.png" },
	{ alias: "midBush4", src: "/assets/scene/middle/mid_bush_4.png" },
	{ alias: "midBush5", src: "/assets/scene/middle/mid_bush_5.png" },
	{ alias: "golfCar", src: "/assets/scene/objects/golf_car.svg" },
	{ alias: "ball", src: "/assets/scene/objects/simple_ball.png" },
	{ alias: "fireBall", src: "/assets/scene/objects/blue_fire_ball.png" },
	{ alias: "holeFlag", src: "/assets/scene/objects/hole_flag.png" },
	{ alias: "bird", src: "/assets/scene/characters/bird.png" },
	{ alias: "bird2", src: "/assets/scene/characters/bird2.png" },
	{ alias: "plane", src: "/assets/scene/aircraft/plane_skins.png" },
	{ alias: "plane2", src: "/assets/scene/aircraft/plane_skins2.png" },
	{ alias: "plane3", src: "/assets/scene/aircraft/plane_skins3.png" },
	{ alias: "helicopter", src: "/assets/scene/aircraft/helicopter_skins.png" },
	{
		alias: "helicopter2",
		src: "/assets/scene/aircraft/helicopter_skins2.png",
	},
	{ alias: "ufo", src: "/assets/scene/space/UFO.png" },
	{ alias: "meteors", src: "/assets/scene/space/meteors.svg" },
	{ alias: "asteroid1", src: "/assets/scene/space/asteroid_1.svg" },
	{ alias: "asteroid2", src: "/assets/scene/space/asteroid_2.svg" },
	{ alias: "asteroid3", src: "/assets/scene/space/asteroid_3.svg" },
	{ alias: "asteroid4", src: "/assets/scene/space/asteroid_4.svg" },
	{ alias: "asteroid5", src: "/assets/scene/space/asteroid_5.svg" },
	{ alias: "asteroid6", src: "/assets/scene/space/asteroid_6.png" },
	{ alias: "asteroid7", src: "/assets/scene/space/asteroid_7.png" },
	{ alias: "asteroid8", src: "/assets/scene/space/asteroid_8.png" },
	{ alias: "asteroid9", src: "/assets/scene/space/asteroid_9.png" },
	{ alias: "cloud1", src: "/assets/scene/clouds/cloud_1.png" },
	{ alias: "cloud2", src: "/assets/scene/clouds/cloud_2.png" },
	{ alias: "cloud3", src: "/assets/scene/clouds/cloud_3.png" },
	{ alias: "cloud4", src: "/assets/scene/clouds/cloud_4.png" },
	{ alias: "cloud5", src: "/assets/scene/clouds/cloud_5.png" },
	{ alias: "cloud6", src: "/assets/scene/clouds/cloud_6.png" },
	{ alias: "cloud7", src: "/assets/scene/clouds/cloud_7.png" },
	{ alias: "cloud8", src: "/assets/scene/clouds/cloud_8.png" },
	{ alias: "cloud9", src: "/assets/scene/clouds/cloud_9.png" },
	{ alias: "cloud10", src: "/assets/scene/clouds/cloud_10.png" },

	// Spine — register json + atlas pairs (see `@esotericsoftware/spine-pixi-v8`).
	{ alias: "spineBirdJson", src: "/assets/animations/bird/export/bird.json" },
	{
		alias: "spineBirdAtlas",
		src: "/assets/animations/bird/export/bird.atlas",
	},
	{ alias: "spineDuckJson", src: "/assets/animations/duck/export/duck.json" },
	{
		alias: "spineDuckAtlas",
		src: "/assets/animations/duck/export/duck.atlas",
	},
	{
		alias: "spineGoldenBirdJson",
		src: "/assets/animations/golden_bird/export/golden_bird.json",
	},
	{
		alias: "spineGoldenBirdAtlas",
		src: "/assets/animations/golden_bird/export/golden_bird.atlas",
	},
	{
		alias: "spineSheikhJson",
		src: "/assets/animations/sheikh/export/sheikh.json",
	},
	{
		alias: "spineSheikhAtlas",
		src: "/assets/animations/sheikh/export/sheikh.atlas",
	},
	{ alias: "spineUfoJson", src: "/assets/animations/ufo/export/ufo.json" },
	{ alias: "spineUfoAtlas", src: "/assets/animations/ufo/export/ufo.atlas" },
	{
		alias: "spineSatelliteJson",
		src: "/assets/animations/satellite/export/satellite.json",
	},
	{
		alias: "spineSatelliteAtlas",
		src: "/assets/animations/satellite/export/satellite.atlas",
	},
] as const;

export type GameManifestEntry = (typeof GAME_ASSET_MANIFEST)[number];

/**
 * Aliases not required for first interactive frame: unused artwork, duplicate paths,
 * or optional Spine (duck flock — no spawner wired yet). Loaded right after core in the background.
 */
export const GAME_DEFERRED_LOAD_ALIASES: ReadonlySet<string> = new Set([
	"starsOverlay",
	"spineDuckJson",
	"spineDuckAtlas",
	"bird",
	"bird2",
	"ufo",
	"fireBall",
	"back",
	"middle",
	"front",
	"frontHole",
	"frontBush1",
	"frontBush2",
	"frontBush3",
	"frontBush4",
	"midBush1",
	"midBush2",
	"midBush3",
	"midBush4",
	"midBush5",
	"water1",
	"water2",
	"water3",
	"water4",
	"water5",
	"sand1",
	"sand2",
	"waterTrap3",
	"cloud1",
	"cloud2",
	"cloud3",
	"cloud4",
	"cloud5",
	"cloud6",
	"cloud7",
	"cloud8",
	"cloud9",
	"cloud10",
]);

export const GAME_CORE_ASSET_MANIFEST: readonly GameManifestEntry[] =
	GAME_ASSET_MANIFEST.filter((e) => !GAME_DEFERRED_LOAD_ALIASES.has(e.alias));

export const GAME_LAZY_ASSET_MANIFEST: readonly GameManifestEntry[] =
	GAME_ASSET_MANIFEST.filter((e) => GAME_DEFERRED_LOAD_ALIASES.has(e.alias));
